//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelinePlatform.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimelinePlatform.Web.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        public static string AmountOfCharacters_Many {
            get {
                return ResourceManager.GetString("AmountOfCharacters_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one character.
        /// </summary>
        public static string AmountOfCharacters_One {
            get {
                return ResourceManager.GetString("AmountOfCharacters_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should contain a valid email address..
        /// </summary>
        public static string ErrorMessage_FieldValueNotEmailAddress {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueNotEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should not contain the characters @..
        /// </summary>
        public static string ErrorMessage_FieldValueNotUsername {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueNotUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string ErrorMessage_FieldValueRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should have at most {0}, but had {1}..
        /// </summary>
        public static string ErrorMessage_FieldValueTooLong_Long {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueTooLong_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should have at most {0}..
        /// </summary>
        public static string ErrorMessage_FieldValueTooLong_Short {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueTooLong_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should have at least {0}, but had {1}..
        /// </summary>
        public static string ErrorMessage_FieldValueTooShort_Long {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueTooShort_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should have at least {0}..
        /// </summary>
        public static string ErrorMessage_FieldValueTooShort_Short {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldValueTooShort_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those passwords do not match. Please consider reentering both and try again..
        /// </summary>
        public static string ErrorMessage_PasswordAndItsConfirmationAreNotEqual {
            get {
                return ResourceManager.GetString("ErrorMessage_PasswordAndItsConfirmationAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sign in attempt. Please consider reentering your credentials and try again..
        /// </summary>
        public static string ErrorMessage_SignInFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_SignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that {0} is already taken..
        /// </summary>
        public static string ErrorMessage_ThatXIsAlreadyTaken {
            get {
                return ResourceManager.GetString("ErrorMessage_ThatXIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
